### ISSUE TITLE
The staging app is stuck on the loading screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2239]
-Tested on FI staging app version 1.4.0(178)
-App is stuck on the loading screen.Not moving forward.

**Comment by AliMeer** [comment]
This should be fixed in 179

**Comment by cakesoft-swati** [comment]
-Tested this issue on staging app version 1.4.0(180)
-But still it is getting stuck on "Generating Recovery Keys" loader modal.

**Comment by AliMeer** [comment]
@cakesoft-swati I just tried this on a ios Device and it worked fine and on ios simulator as well.

**Comment by cakesoft-swati** [comment]
Could this be a device-specific problem? Because I have deleted and reinstalled it several times, still not running.

**Comment by Arpanjainson** [comment]
@Varunram  do u have iPhone7?

**Comment by cakesoft-swati** [comment]
-Verified this on Staging app version 1.4.0(182)
-Now it is working.
